[project]
name = "scripting-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "en-core-web-lg",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "spacy>=3.8.13",
    "tqdm>=4.67.3",
]

[tool.uv.sources]
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }
